#!/usr/bin/python

#!/usr/bin/python

try:
   fh = open("file_name", "w")
   try:
      fh.write("This is my test file for exception handling!!")
   finally:
      print ("Going to close the file")
      fh.close()
except IOError:
   print ("Error: can\'t find file or read data")